### ISSUE TITLE
Python 3.5.2. Can't import Device

### ISSUE THREAD

**Issue by wavic** [freenas/py-SMART#14]
I have followed the examples but I get this error:

> from pySMART import Device
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pySMART/__init__.py", line 102, in <module>
    from .device import Device
  File "/usr/local/lib/python3.5/dist-packages/pySMART/device.py", line 33, in <module>
    from .utils import *
  File "/usr/local/lib/python3.5/dist-packages/pySMART/utils.py", line 125, in <module>
    for line in _stdout.split('\n'):
TypeError: a bytes-like object is required, not 'str'

There is no such an error when I  use Python 2

**Comment by swanhart** [comment]
I'm getting the same error when trying to use 
from pySMART import DEVICE

**Comment by BoehmFloh** [comment]
same here

Is there a way to fix this problem?

**Comment by freqlabs** [comment]
Should have been fixed by #11
