### ISSUE TITLE
python 3.8 logging findCaller() error

### ISSUE THREAD

**Issue by lleseur** [freenas/py-SMART#30]
When using pySMART with logging, trying to log throws an exception.

Steps to reproduce:
```
import logging
import pySMART

logger = logging.getLogger(__name__)
logger.critical('message')
```

Result:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    logger.critical('message')
  File "/usr/lib/python3.8/logging/__init__.py", line 1481, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1565, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
```

Expected result:
```
message
```

**Comment by william-gr** [comment]
This library is no being maintained. However if you want to contribute with a PR we will gladly review it.
